projects/mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'), # django.contib.auth 앱의 LoginView 클래스를 활용 -> views.py 파일 수정 필요 없음
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), # pybo 앱 관련 urls.py파일을 따로 구성, pybo/ 시작하는 페이지 요청 -> pybo/urls.py 참고
    path('common/', include('common.urls')), # common 앱의 urls.py파일을 사용하기 위한 코드
    path('', base_views.index, name='index'), # /페이지에 해당하는 urlpatterns
] # 호스트명, 포트는 환경에 따라 변화 + 장고가 이미 알고 있는 값 -> urlpatterns에 입력X

projects/mysite/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name='pybo' # URL별칭에서 중복문제 해결을위한 네임스페이스 과정

urlpatterns = [
    path('', base_views.index,name='index'), # config/urls.py에서 pybo/에 대해 처리 -> 빈 문자열 넘기기, /pybo/ = index
    path('<int:question_id>/', base_views.detail, name='detail'), # question_id에 값 저장된 후 views.detail 함수 실행, /pybo/2/ = detail
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify,
         name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete,
         name='question_delete'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question,
         name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question,
         name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question,
         name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer,
         name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer,
         name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer,
         name='comment_delete_answer'),
    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/',
         vote_views.vote_answer, name='vote_answer'),
]

projects/mysite/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Question



def index(request): # request : 장고에 의해 자동으로 전달되는 HTTP요청 객체, 사용자가 전달한 데이터 확인할 때 사용
    '''
    pybo 목록 출력
    '''
    # 입력인자
    page = request.GET.get('page', '1') #페이지 , GET 방식 요청 URL에서 page값을 가져올 때 사용
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    #정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    # 조회

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()


    # 페이징 처리
    paginator = Paginator(question_list, 10) #페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list' : page_obj, 'page' : page, 'kw' : kw, 'so' : so}
    return render(request, 'pybo/question_list.html', context) # context에 있는 question_list를 pybo/question_list.html 파일에 적용하여 HTML 코드로 변환


def detail(request, question_id):
    '''
    pybo 내용 출력
    '''
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'pybo/question_detail.html', context)

projects/mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css"href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<!-- base.html 파일을 상속한 파일에서 구현해야하는 영역 -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.3.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>
</body>
</html>

projects/mysite/templates/form_errors.html
<!-- 로그인 실패 시 로그인이 실패한 원인을 알려줌 -->

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} <!-- 필드 오류(입력값이 누락 혹은 형식에 맞지 않음)를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!-- 넌필드 오류(입력값과 관계없이 발생한 오류) -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

projects/mysite/templates/navbar.html
<!-- include : 템플릿 특정 위치에 템플릿 파일 삽입하는 기능 (특정 영역을 중복,반복해서 사용할 경우 유용) -->
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>